define({
    "compile_button" : "コンパイル",
    "controller" : "再生",
    "stop_button" : "ストップ",
    "new_button" : "新規",
    "open_button" : "開く",
    "open_from_empty" : "保存元を選択してください",
    "select_box_LOCAL" : "ローカルストレージ",
    "select_box_SERVER" : "サーバー",
    "select_box_FILE" : "ローカルファイル",
    "save_button" : "保存",
    "save_as_empty" : "保存先を選択してください",
    "piano_roll_pane_title" : "ピアノロール",
    "editor_pane_title" : "MMLソース",
    "AST_pane_title" : "構文木",
    "help_pane_title" : "ヘルプ",
    "music_info_pane_title" : "曲情報",
    "track_selector_label" : "トラックナンバー",
    "music_title_label" : "タイトル",
    "note_property_pane_title" : "プロパティー",
    "velocity_label" : "ベロシティー",
    "settings_pane_title" : "設定",
    "progress_bar_dialog_title" : "進捗状況",
    "help_file_url" : "help_ja.html"
});