define({
    root: {
        "compile_btn_text" : "Compile",
        "play_btn_text" : "Play",
        "stop_btn_text" : "Stop",
        "new_btn_text" : "New",
        "open_btn_text" : "Open",
        "open_label_text" : "Open from :",
        "open_explanation" : "Choose a desired method",
        "type_LOCAL" : "Using local storage",
        "type_SERVER" : "Upload to the server",
        "type_FILE" : "Save to",
        "open_prompt" : "Choose a title to open",
        "save_btn_text" : "Save",
        "save_label_text" : "Save to :",
        "save_explanation" : "Choose a desired method",
        "piano_roll_pane_title" : "Piano Roll",
        "editor_pane_title" : "MML source text",
        "AST_pane_title" : "AST",
        "help_pane_title" : "Help",
        "music_info_pane_title" : "Music infos",
        "track_selector_label" : "Track Num",
        "music_title_label" : "Title",
        "author_label" : "Author",
        "note_property_pane_title" : "Properties",
        "velocity_label" : "Velocity",
        "settings_pane_title" : "Preferences",
        "progress_bar_dialog_title" : "Progress",
        "help_file_url" : "help_en.html",
        "msg_prompt_compiling" : "The source text is not compiled yet.\n Please use the \"Compile\" button on the first attempt to play.",
        "warning_not_saved" : "The file currently opened found to be not saved. Would you like to save that file first?",
        "msg_new_file_opened" : "Successfully created a new file.",
        "msg_file_opened" : "Successfully opened a file.",
        "msg_file_saved" : "Successfully saved the file.",
        "msg_save_failed" : "Failed to save.",
        "no_file_name" : "Untitled",
        "last_modified" : "Last modified at",
        "connect_to_server" : "Connecting to the server...",
        "received_responce" : "Received responce from the server"
    },
    
    ja : true
});